### ISSUE TITLE
Hardware doesn't start

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/amigo_hardware#10]
At running ahardware, the robot clicks, lights turn white for a fraction of a second and then turn off again. These are the error messages:

3.237 [ ERROR  ][Soem] Time:    4708.562 SDO slave:13 index:1c13.01 error:06090011 Subindex does not exist

3.237 [ ERROR  ][Soem] 
5.653 [ ERROR  ][ScriptingService] Not all slaves reached operational state.
5.653 [ ERROR  ][ScriptingService] Slave 1 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 2 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 3 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 4 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 5 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 6 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 7 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 8 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 9 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 10 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 11 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 12 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 13 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 14 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 15 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 16 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 17 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 18 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 19 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 20 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 21 State= 2 StatusCode=0 : No error
5.653 [ ERROR  ][ScriptingService] Slave 22 State= 2 StatusCode=0 : No error
5.654 [ ERROR  ][ScriptingService] Slave 23 State= 2 StatusCode=0 : No error
6.892 [ ERROR  ][ScriptingService] Supervisor: No soem heartbeat found
7.485 [ Warning][ScriptingService] TrajectoryActionlib: Total of 1 joints for 1 Bodyparts
7.946 [ Warning][ScriptingService] TrajectoryActionlib: Total of 8 joints for 2 Bodyparts

**Comment by MaxBaeten** [comment]
Known bug, probably inside FPGA code that was made by EPC. Restart and it will work. So annoying bug but restarting will fix it.
