### ISSUE TITLE
[Soem] Receiving data failed

### ISSUE THREAD

**Issue by svddries** [tue-robotics/amigo_hardware#11]
Got the hardware working besides the arms (they crash when homing), but after 5 minutes everything crashed:

3.148 [ ERROR  ][Soem] Time:     773.688 SDO slave:13 index:1c13.01 error:06090011 Subindex does not exist

3.148 [ ERROR  ][Soem] 
4.393 [ Warning][ScriptingService] TrajectoryActionlib: Total of 1 joints for 1 Bodyparts
4.834 [ Warning][ScriptingService] TrajectoryActionlib: Total of 8 joints for 2 Bodyparts
5.574 [ Warning][ScriptingService] TrajectoryActionlib: Total of 15 joints for 3 Bodyparts
[ INFO] [1441022590.512027239]: Calibration finished. Latency is: -0.0420
   Switched to : HARDWARE

  This console reader allows you to browse and manipulate TaskContexts.
  You can type in an operation, expression, create or change variables.
  (type 'help' for instructions and 'ls' for context info)

    TAB completion and HISTORY is available ('bash' like)

    Use 'Ctrl-D' or type 'quit' to exit this program.

HARDWARE [S]> [ INFO] [1441022590.812050564]: Streaming data.
17.841 [ Warning][Logger] Supervisor: Received Start request from dashboard for partNr: [1]
17.841 [ Warning][Logger] Supervisor::GoOperational: Allowing bodypart:     [1]
18.921 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [Supervisor: Received Homing request from dashboard for partNr: [2]
18.921 [ Warning][Logger] Supervisor::GoHoming: Allowing bodypart:     [2]
22.401 [ Warning][Logger] Supervisor: Received Start request from dashboard for partNr: [5]
22.401 [ Warning][Logger] Supervisor::GoOperational: Allowing bodypart:     [5]
22.401 [ Info   ][Logger] 
25.245 [ Warning][Logger] SPINDLE_Homing: Finished homing of last joint 1. 

25.252 [ Warning][Logger] SPINDLE_Homing: Finished homing joints of spindle: [1, ]!
25.252 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [1,1,0,0,1]
25.281 [ Warning][Logger] Supervisor::GoOperational: Allowing bodypart:     [2]
517.739 [ Warning][Soem] receiving data failed
517.751 [ Warning][Soem] receiving data failed
517.755 [ Warning][Soem] receiving data failed
517.759 [ Warning][Soem] receiving data failed
517.763 [ Warning][Soem] receiving data failed
517.767 [ Warning][Soem] receiving data failed
517.771 [ Warning][Soem] receiving data failed
517.775 [ Warning][Soem] receiving data failed
517.779 [ Warning][Soem] receiving data failed
517.783 [ Warning][Soem] receiving data failed
517.787 [ Warning][Soem] receiving data failed
517.791 [ Warning][Soem] receiving data failed
517.795 [ Warning][Soem] receiving data failed
517.799 [ Warning][Soem] receiving data failed
517.803 [ Warning][Soem] receiving data failed
517.807 [ Warning][Soem] receiving data failed
517.811 [ Warning][Soem] receiving data failed
517.819 [ Warning][Soem] receiving data failed
517.823 [ Warning][Soem] receiving data failed
517.827 [ Warning][Soem] receiving data failed
517.831 [ Warning][Soem] receiving data failed
517.835 [ Warning][Soem] receiving data failed
517.843 [ Warning][Soem] receiving data failed
517.847 [ Warning][Soem] receiving data failed
517.851 [ Warning][Soem] receiving data failed
517.855 [ Warning][Soem] receiving data failed
517.859 [ Warning][Soem] receiving data failed
517.863 [ Warning][Soem] receiving data failed
517.867 [ Warning][Soem] receiving data failed
517.871 [ Warning][Soem] receiving data failed
517.875 [ Warning][Soem] receiving data failed
517.879 [ Warning][Soem] receiving data failed
517.883 [ Warning][Soem] receiving data failed
517.887 [ Warning][Soem] receiving data failed
517.891 [ Warning][Soem] receiving data failed
517.895 [ Warning][Soem] receiving data failed
517.899 [ Warning][Soem] receiving data failed
517.903 [ Warning][Soem] receiving data failed
517.907 [ Warning][Soem] receiving data failed
517.911 [ Warning][Soem] receiving data failed
517.915 [ Warning][Soem] receiving data failed
517.919 [ Warning][Soem] receiving data failed
517.923 [ Warning][Soem] receiving data failed
517.927 [ Warning][Soem] receiving data failed
517.931 [ Warning][Soem] receiving data failed
517.935 [ Warning][Soem] receiving data failed
517.939 [ Warning][Soem] receiving data failed
517.943 [ Warning][Soem] receiving data failed
517.947 [ Warning][Soem] receiving data failed
517.955 [ Warning][Soem] receiving data failed
517.959 [ Warning][Soem] receiving data failed
517.963 [ Warning][Soem] receiving data failed
517.967 [ Warning][Soem] receiving data failed
517.971 [ Warning][Soem] receiving data failed
517.975 [ Warning][Soem] receiving data failed
517.979 [ Warning][Soem] receiving data failed
517.983 [ Warning][Soem] receiving data failed
517.987 [ Warning][Soem] receiving data failed
517.991 [ Warning][Soem] receiving data failed
517.995 [ Warning][Soem] receiving data failed
517.999 [ Warning][Soem] receiving data failed
518.003 [ Warning][Soem] receiving data failed
518.007 [ Warning][Soem] receiving data failed
518.011 [ Warning][Soem] receiving data failed
518.015 [ Warning][Soem] receiving data failed
518.019 [ Warning][Soem] receiving data failed
518.027 [ Warning][Soem] receiving data failed
518.031 [ Warning][Soem] receiving data failed
... etc ...
526.175 [ Warning][Soem] Max out queue size reached on 0. Throwing away old bytes...
526.175 [ Warning][Soem] Max out queue size reached on 0. Throwing away old bytes...
526.175 [ Warning][Soem] Max out queue size reached on 0. Throwing away old bytes...
526.176 [ Warning][Soem] Max out queue size reached on 0. Throwing away old bytes...In AnalogInsGeneric: Using old data for inport beckhoffmsg_in_1
526.176 [ Warning][Soem] Max out queue size reached on 0
526.176 [ Warning][Soem] Max out queue size reached on 0. Throwing away old bytes...
526.176 [ Warning][Soem] Max out queue size reached on 0. Throwing away old bytes...
526.176 [ Warning][Soem] Max out queue size reached on 0. Throwing away old bytes...
526.176 [ Warning][Soem] DynamixelController: waiting for data
526.176 [ Warning][Soem] In AnalogInsGeneric: Using old data for inport beckhoffmsg_in_1
526.183 [ Warning][Soem] receiving data failed
526.187 [ Warning][Soem] receiving data failed
526.191 [ Warning][Soem] receiving data failed
526.195 [ Warning][Soem] receiving data failed
... etc ...

**Comment by Rayman** [comment]
Is this the same as #9?

**Comment by MaxBaeten** [comment]
Not the same as #9, And I'll close this one since it has been investigated numerous times but it basically requires a redesign of the ebus connection.
