### ISSUE TITLE
Set priorities to 45 instead of 99

### ISSUE THREAD

**Issue by Timple** [tue-robotics/amigo_hardware#16]
Understanding priorities better now, setting a priority of 99 is not very smart. The orocos components will take precedence even over the CPU scheduler!
The networking stack is at 50. So I would go slightly below that to give even communication a higher priority than the orocos components.

This will still be higher than other ros components on this PC, which is what we actually intended in the past

**Comment by MatthijsBurgh** [comment]
see tue-robotics/amigo_bringup#80

**Comment by MatthijsBurgh** [comment]
fixed by tue-robotics/amigo_bringup#80
