### ISSUE TITLE
Hardware reset

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/amigo_hardware#5]
Hardware reset does not work: the error of one or more joints is too large. Do you already start and stop the controllers as we did before? Calling the starthook makes these things a lot easier!

**Comment by MaxBaeten** [comment]
I will have a look at this after I implemented the new global reference generator

**Comment by rokusottervanger** [comment]
Can this be closed?

**Comment by MaxBaeten** [comment]
It is not solved yet so i would leave it open

**Comment by svddries** [comment]
I had the issue that after I toggled the emergency switch, the left arm got into error. Is this the same problem? Output:

[ INFO] [1442402387.678774053]: Supervisor: Emergency button pressed, shutting down components online components
100.339 [ Warning][Logger] Supervisor::GoIdle: Allowing bodypart:     [1]
100.340 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [0,1,1,1,1]
100.340 [ Warning][Soem] Supervisor::GoIdle: Allowing bodypart:     [2]
100.341 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [0,0,1,1,1]
100.342 [ Warning][Logger] Supervisor::GoIdle: Allowing bodypart:     [3]
100.343 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [0,0,0,1,1]
100.347 [ Warning][Logger] Supervisor::GoIdle: Allowing bodypart:     [4]
100.347 [ Warning][Logger] Supervisor::GoIdle: Allowing bodypart:     [5]
100.348 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [0,0,0,0,0]
[ INFO] [1442402390.798751845]: Supervisor: Emergency button released, restoring components
103.458 [ Warning][Logger] Supervisor::GoOperational: Allowing bodypart:     [1]
103.459 [ Warning][Logger] Supervisor::GoOperational: Allowing bodypart:     [2]
103.459 [ Warning][Logger] Supervisor::GoOperational: Allowing bodypart:     [3]
103.460 [ Warning][Logger] Supervisor::GoOperational: Allowing bodypart:     [4]
103.460 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [Supervisor::GoOperational: Allowing bodypart:     [5]
103.461 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [1,1,1,1,1]
[ERROR] [1442402390.803715731]: Safety: Error of joint q1 exceeded limit (0.09). jointErrors[0] = 0.0997792 output disabled.
103.463 [ Debug  ][Logger] 
103.502 [ Warning][Logger] LPERA_Safety: Error of joint q1 exceeded limit (0.09Supervisor::GoError: Allowing bodypart:     [3]
103.503 [ Warning][Logger] TrajectoryActionlib:  Allowed:     [1,1,0,1,1

**Comment by MaxBaeten** [comment]
No that is a different problem. I will look into that soon. This bug is btw something that has my attention but isn't a high prio imo. Sjoerds issue is of higher prio and I will look into that once I am near the robot

**Comment by MaxBaeten** [comment]
Hardware reset works. Although not implemented the way you suggested above janno. I will have to look into that after RC Germany.
